---
# Source: ritotalks/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "backend"
  namespace: "production"
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ritotalks
    app.kubernetes.io/instance: rt-production
    app.kubernetes.io/managed-by: "Helm"
spec:
  
  ports:
    -
      name: http
      port: 8080
      targetPort: 4567
  selector:
    app: "backend"
---
# Source: ritotalks/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "backend"
  namespace: "production"
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ritotalks
    app.kubernetes.io/instance: rt-production
    app.kubernetes.io/managed-by: "Helm"
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        timestamp: '"2021-03-27 10:17:35.234721 +0300 MSK m=+0.114474210"'
      labels:
        app: backend
    spec:
      # nodeSelector:
      #   env: ''
      terminationGracePeriodSeconds: 120
      containers:
        - name: backend
          image: "docker.io/library/nodebb-backend:release"
          imagePullPolicy: Always
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "AWS_REGION"
              value: "us-east-1"
            - name: "AWS_S3_BUCKET"
              value: "s3-ritotalks-cdn"
            - name: "MONGO_DATABASE"
              value: "nodebb"
            - name: "MONGO_HOST"
              value: "rt-mongodb-production-0"
            - name: "MONGO_PASS"
              value: "awesomepassword1"
            - name: "MONGO_PORT"
              value: "27017"
            - name: "MONGO_USER"
              value: "nodebb"
            - name: "NODE_ENV"
              value: "production"
          command:
            - /bin/bash
            - -c
            - /opt/nodebb/start.sh
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"
---
# Source: ritotalks/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rt-production-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 3
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
---
# Source: ritotalks/templates/configs/conf.yaml
# Example for additional files with config in container
