---
{{- range $name, $app := .Values.apps }}
{{ if and (hasKey $app "service") (hasKey $app.service "ingress") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $name }}"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: nginx
{{ include "common_labels" $ | indent 4 }}
spec:
  rules:
    - host: '{{ $app.service.ingress.domain }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ $name }}'
                port:
                  {{- with (first $app.service.ports) }}
                  number: {{ .port }}
                  {{- end }}
---
{{- end }}
{{- end }}
