{{- if .Values.secrets_env }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ $.Release.Name }}"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-weight: '-1'
{{ include "common_labels" $ | indent 4 }}
spec:
  backendType: secretsManager
  dataFrom:
  - "{{ .Values.secrets_env.name }}"
{{- end }}
