---
nodeSelector: ''

image:
  tag: release

ingress:
  certificate_arn: ''
  group: ''
  subnets: ''

# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 80
#       preference:
#         matchExpressions:
#         - key: eks.amazonaws.com/capacityType
#           operator: In
#           values:
#             - SPOT

# jobs:

#   psql-migrate-job:
#     env:
#       NODE_ENV: production
#       MONGO_DATABASE: nodebb
#       MONGO_HOST: mongodb-headless.local.svc.cluster.local
#       MONGO_PORT: 27017
#       MONGO_USER: nodebb
#       MONGO_PASS: awesomepassword1

#   psql-seed-job:
#     env:
#       NODE_ENV: production
#       MONGO_DATABASE: nodebb
#       MONGO_HOST: mongodb-headless.local.svc.cluster.local
#       MONGO_PORT: 27017
#       MONGO_USER: nodebb
#       MONGO_PASS: awesomepassword1

apps:

  nodebb:
    replicaCount: 1
    resources:
      cpu: 250m
      cpu_limit: 750m
      memory: 512Mi
      memory_limit: 1024Mi
    autoscaler_enabled: true
    autoscaler_min: 1
    autoscaler_max: 25
    target_cpuutilization: 80
    service:
      ingress:
        domain: ritotalks.ru
        scheme: internet-facing
    env:
      AWS_REGION: us-east-1
      AWS_S3_BUCKET: s3-ritotalks-cdn

      S3_UPLOADS_BUCKET: s3-ritotalks-cdn
      S3_UPLOADS_HOST: https://cdn.ritotalks.ru
      S3_UPLOADS_PATH: /local

      NODE_ENV: production
      NODEBB_URL: http://ritotalks.ru
      NODEBB_PORT: 8080
      NODEBB_SECRET: CTsNDeHNHX9jBnQFgz9WbqkhsQaA24vj
      MONGO_DATABASE: nodebb
      MONGO_HOST: mongodb-headless.local.svc.cluster.local
      MONGO_PORT: 27017
      MONGO_USER: nodebb
      MONGO_PASS: awesomepassword1
      REDIS_HOST: redis-headless.local.svc.cluster.local
      REDIS_PORT: 6379
      REDIS_PASS: awesomepassword2
      REDIS_DATABASE: 0

# secrets_env:
#   name: sm-ritotalks-production
#   keys:
#     AMAZON_S3_SECRET_KEY: aws_secret_access_key
#     AMAZON_S3_ACCESS_KEY: aws_access_key_id
